In [1]:
import numpy as np

In [ ]:
'''
numpy : 고성능 과학(수치) 계산을 위한 데이터 분석(수치분석) 패키지
    - 벡터 산술연산
    - 다차원 배열 (ndarray)
    - 표준 수학 함수
    - 선형대수, 난수
    
numpy 배열 : 같은 종류의 데이터를 담는 자료형 (동일한 타입의 값)
    - rank : 배열의 차원 (ndim)
    - shape : 각 차원의 크기를 튜플로 리턴 (행, 열)
    - dtype : 배열에 저장된 자료(타입)를 알려주는 객체

ndarray : 다차원 배열 객체
    - array() : 배열 생성
    - arange() : 배열 생성 시 지정 값까지 자동 생성
    - reshape() : 배열 모양 변경
    - zeros() : 0이 들어있는 배열 생성
    - ones() : 1이 들어있는 배열 생성
    - full() : 모든 값이 특정 상수인 배열을 생성
    - eye() : 단위 행렬 생성

'''

In [2]:
import numpy as np

In [5]:
# rank가 1인 배열을 생성

a = np.array([1, 2, 3])
b = [1, 2, 3]
print(a)
print(b)

[1 2 3]
[1, 2, 3]


In [6]:
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'list'>


In [7]:
a.shape  # 3행 1렬

(3,)

In [8]:
a.ndim

1

In [10]:
# 2차원 배열을 생성
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [11]:
b.dtype  # int32 -> 같은 int지만 int32, int64등 다른 자료형으로 인식될 것들이 존재함
        # 배열에 저장된 자료의 type

dtype('int32')

In [12]:
a.itemsize  # 각 배열 요소가 메모리 상에 차지하고 있는 크기 : byte단위
            # 4byte니까 int32 bit?
            # 보통 int는 4byte

4

In [13]:
arr = np.arange(12)  # arange : 0부터 시작임에 유의
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
# 3행 4열 형태로 만들기
arr = np.arange(12).reshape(3, 4); arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
arr.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.full((3, 3), 9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# 활용 - 임의의 데이터가 필요할 때
np.random.random((2, 2))

array([[0.66146168, 0.86418884],
       [0.64775602, 0.65658342]])

In [ ]:
'''
배열 인덱싱
    - 슬라이싱 : 파이썬 리스트를 다루는 것과 유사하게 numpy에서도 슬라이싱이 가능
            : 슬라이싱된 배열은 원본 배열과 같은 데이터를 참조함 -> 슬라이싱된 배열 수정하면 원본도 바뀜
            : numpy 배열을 슬라이싱하면 그 결과는 언제나 원본 배열의 부분 배열임.
            
    - 인덱싱 : numpy 배열 인덱싱은 팬시 인덱싱(fancy indexing)이라고도 함.
            : 배열 인덱싱의 유용한 기능 중 하나가 행렬의 각 행에서 하나의 요소를 선택하거나 바꾸는 기능
            : 정수 배열 인덱싱을 하는 경우는 원본과 다른 배열을 만들 수 있다.

'''

In [22]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
# 슬라이싱
# 1, 2, 5, 6을 가져오고 싶음.
b = a[:2, :2]
b

array([[1, 2],
       [5, 6]])

In [ ]:
# 2, 3, 6, 7을 가져오고 싶음.

In [31]:
c = a[:2, 1:3]
c

array([[2, 3],
       [6, 7]])

In [32]:
# 인덱싱
b[0, 0]

1

In [36]:
b[0, 0] = 100
print(b)  # 부분집합을 수정하니까
print(a)  # 원본도 수정됨

[[100   2]
 [  5   6]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [37]:
# 5, 6, 7, 8 을 가져오기(행) => 2번째 행을 가져오기
d = a[1, :]
d

array([5, 6, 7, 8])

In [38]:
print(d.ndim)  # rank = 1
print(d.shape) # 4개의 데이터(튜플이라서 3,로 표기한 것)

1
(4,)


In [39]:
# 2, 6, 10 을 가져오기(열) => 2번째 열을 가져왔음, 근데 rank가 1 --> 1행짜리로 가져온듯?
e = a[:, 1]
e

array([ 2,  6, 10])

In [40]:
print(e.ndim)  # rank = 1
print(e.shape) # 3개의 데이터(튜플이라서 3,로 표기한 것)

1
(3,)


In [42]:
# 2, 6, 10을 열 형태로 가져오기
f = a[:, 1:2]; f

array([[ 2],
       [ 6],
       [10]])

In [43]:
print(f.ndim)  # rank = 2
print(f.shape) # 3행 1열

2
(3, 1)


In [45]:
# 
a = np.array([[1, 2], [3, 4], [5, 6]]); a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
b = a[[0, 1, 2], [0, 1, 0]]  # a(0,0) (1,1) (2,0) 추출
b

array([1, 4, 5])

In [48]:
b.shape

(3,)

In [51]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]); a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
idx = np.array([0,0,0,0,1,1,1,1,2,2,2]); idx

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2])

In [52]:
a[idx]  # 배열의 크기가 달라도 idx에 있는 데이터 그대로 a 인덱싱된 데이터 빼 옴

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3])

In [53]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 부울 인덱싱

In [54]:
a = np.array([[1, 2], [3, 4], [5, 6]]); a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [55]:
g = a[:, [True, False]]; g  # 가져오고 싶은 열을 True, 아니면 False

array([[1],
       [3],
       [5]])

In [56]:
g.shape

(3, 1)

In [ ]:
'''
배열 연산
    - 기본은 배열의 각 요소별로 동작.
    - 수학함수, 연산자, numpy 함수 모듈을 통해 배열 연산이 가능
'''

In [57]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

In [58]:
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [59]:
x + y

array([[ 6,  8],
       [10, 12]])

In [60]:
np.add(x, y)

array([[ 6,  8],
       [10, 12]])

array([[ 5, 12],
       [21, 32]])