# 난수(random number)

In [ ]:
'''
# 난수 발생 : np.rand() - 0부터 1사이의 실수
# seed(씨앗값) : 보통 프로그래밍 언어는 난수값이 보통 설정되어있음
              : 조금 더 난수를 만들고 싶으면 씨앗값을 바꾸는 형태로 사용

'''

In [1]:
import numpy as np

In [2]:
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [3]:
np.random.rand(5)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [4]:
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [5]:
np.random.seed(2)    # 시드를 바꾸면 그때그때 다른 난수 가능
np.random.rand(5)

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ])

In [9]:
for i in range(10):
    print(np.random.rand())

0.22601200060423587
0.10694568430998297
0.2203062070705597
0.34982628500329926
0.46778748458230024
0.20174322626496533
0.6404067252149148
0.48306983555175165
0.5052367200185491
0.3868926511185593


In [10]:
np.random.rand(10)

array([0.79363745, 0.58000418, 0.1622986 , 0.70075235, 0.96455108,
       0.50000836, 0.88952006, 0.34161365, 0.56714413, 0.42754596])

In [11]:
# shuffle
x = np.arange(10)
print(x)
print('----------------------')
np.random.shuffle(x)
print(x)

[0 1 2 3 4 5 6 7 8 9]
----------------------
[7 6 9 0 3 5 1 4 2 8]


In [ ]:
'''
# 데이터 샘플링 : 이미 있는 데이터 집합에서 무작위로 선택하는 것 (sampling)
# np.random.choice (원본데이터, size, replace=True/False, p)

- 원본 데이터 : (range(원본데이터))
- size : 샘플 숫자
- replace : True이면 한 번 선택한 데이터를 다시 선택할 수 있음
- p : 각 데이터가 선택될 수 있는 확률
'''

In [12]:
x = np.random.choice(5, 5, replace=False); x

array([3, 2, 1, 0, 4])

In [13]:
x1 = np.random.choice(5, 3, replace=False); x1

array([0, 2, 3])

In [14]:
x2 = np.random.choice(5, 10, replace=False); x2

ValueError: Cannot take a larger sample than population when 'replace=False'

In [15]:
x2 = np.random.choice(5, 10, replace=True); x2      # 재사용을 하면 원본데이터보다 더 많은 값 추출 가능

array([2, 4, 2, 3, 4, 2, 0, 2, 3, 3])

In [16]:
x3 = np.random.choice(5, 10, replace=True, p=[0.1, 0, 0, 0.3, 0.6]); x3  # 요소별 선택 확률도 부여

array([4, 4, 3, 4, 4, 4, 4, 4, 4, 4])

In [ ]:
'''
# rand() : 0~1 실수 균일 분포
# randn() : 실수 가우시안 표준 정규 분포
# randint() : 균일분포 정수 - 난수
 - randint(low, high, size)
  -- size : 난수의 갯수

'''

In [17]:
np.random.rand(5)

array([0.39393329, 0.92654675, 0.00554442, 0.7284985 , 0.35575363])

In [18]:
np.random.rand(3, 5)

array([[0.21293324, 0.36202741, 0.87830029, 0.36332589, 0.50320692],
       [0.76748826, 0.91447557, 0.82636801, 0.41174644, 0.63084266],
       [0.3419116 , 0.38169294, 0.96245957, 0.64701423, 0.95784567]])

In [22]:
np.random.randn(10)

array([ 0.15550392,  1.48506087, -0.3951954 ,  0.65063129,  0.01786335,
       -1.17113099, -0.95819534, -0.46706884,  0.55772101, -0.46522933])

In [23]:
np.random.randint(10, 50, 5)

array([47, 35, 46, 25, 31])

In [31]:
# 로또 번호 6개 구해보세요
np.random.randint(1, 46, 6)

array([22, 42, 37, 42, 41, 20])

In [33]:
# 로또 5천원어치 구해보세요
np.random.randint(1, 46, [5,6])

array([[28, 17,  5, 13, 35, 24],
       [42, 20, 34, 32, 18, 26],
       [10,  1,  9, 11,  9, 38],
       [36, 41, 36, 15, 16, 45],
       [ 7, 34, 35, 32, 30, 35]])

In [41]:
# cf) 큰 값을 선언하지 않고 배열로 만드는 방법
np.empty((4, 3))

array([[1.11250650e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.88648123e-062],
       [7.24893897e+169, 3.60282746e+175, 1.23162090e+165],
       [9.59580151e-071, 5.69860862e-038, 4.43046942e+175]])