In [1]:
'''
# numpy 기술 통계 (Descriptive statistics)
 - 평균(mean) : np.mean(x)
 - 분산(variance) : 데이터와 샘플 평균간 거리의 제곱의 평균
                  : 이 값이 작으면 데이터가 모여 있는 것, 이 값이 크면 흩어져 있는 것
                  : np.var(x)
 - 표준편차(standard deviation) : 분산의 제곱근 값.
                  : np.std(x)
 - 최대값(maximum) : 데이터 중에서 가장 큰 값 - np.max(x)
 - 최소값(minimum) : 데이터 중에서 가장 작은 값 - np.min(x)
 - 중앙값(median) : 데이터를 크기 대로 정렬 하였을 때 가장 가운데에 있는 수
                 : 가장 가운데에 있는 수가 2개이면? 중앙 두 수의 평균을 사용
                 : np.median(x)
 - 사분위수(quartile) : 데이터를 크기대로 정렬하였을 때 1/4, 2/4, 3/4 위치에 있는 수
                     : 1사분위수, 2사분위수, 3사분위수
                     
                     : 데이터가 100개라면 25번째 순서까지가 1사분위수
                     : 위치를 1/100 단위로 나눈 백분위수(percentile)를 사용하기도 함
                       이 때는 1사분위수는 25%
                 : np.percentile(x, 0)   # 최소값
                 : np.percentile(x, 25)  # 1사분위수
                 : np.percentile(x, 50)  # 2사분위수
                 : np.percentile(x, 75)  # 3사분위수
                 : np.percentile(x, 100)  # 최대값
                 
  - 합계 : np.sum()
  - 여러 개의 수를 연속하여 곱하기 : np.product()
 
'''

'\n# numpy 기술 통계 (Descriptive statistics)\n - 분산(variance) : 데이터와 샘플 평균간 거리의 제곱의 평균\n                  : 이 값이 작으면 데이터가 모여 있는 것, 이 값이 크면 흩어져 있는 것\n                  : np.var(x)\n - 표준편차(standard deviation) : 분산의 제곱근 값.\n                  : np.std(x)\n - 최대값(maximum) : 데이터 중에서 가장 큰 값 - np.max(x)\n - 최소값(minimum) : 데이터 중에서 가장 작은 값 - np.min(x)\n - 중앙값(median) : 데이터를 크기 대로 정렬 하였을 때 가장 가운데에 있는 수\n                 : 가장 가운데에 있는 수가 2개이면? 중앙 두 수의 평균을 사용\n                 : np.median(x)\n - 사분위수(quartile) : 데이터를 크기대로 정렬하였을 때 1/4, 2/4, 3/4 위치에 있는 수\n                     : 1사분위수, 2사분위수, 3사분위수\n                     \n                     : 데이터가 100개라면 25번째 순서까지가 1사분위수\n                     : 위치를 1/100 단위로 나눈 백분위수(percentile)를 사용하기도 함\n \n \n \n'

In [2]:
import numpy as np

In [3]:
x = np.array([18, 5, 10, 2, 3, 11, -3, -5, -30, 15, 6, 78, -13, 9, 5, 6, 7, 3, 80, -4]); x

array([ 18,   5,  10,   2,   3,  11,  -3,  -5, -30,  15,   6,  78, -13,
         9,   5,   6,   7,   3,  80,  -4])

In [4]:
len(x)

20

In [5]:
# 평균
np.mean(x)

10.15

In [6]:
# 분산
np.var(x)

629.3274999999999

In [7]:
# 표준편차
np.std(x)

25.086400698386363

In [8]:
# 최대값, 최소값, 중앙값
print(np.max(x))
print(np.min(x))
print(np.median(x))

80
-30
5.5


In [10]:
# 사분위수
print(np.percentile(x, 0))
print(np.percentile(x, 25))
print(np.percentile(x, 50))
print(np.percentile(x, 75))
print(np.percentile(x, 100))

-30.0
0.75
5.5
10.25
80.0


In [11]:
# 합계
np.sum(x)

203

In [12]:
# 연속 곱
np.product(x)

-959193088

# 선형대수

In [ ]:
'''
# 선형대수(linear algebra) : 데이터 분석에 필요한 여러 계산을 돕기 위한 학문
 > 데이터 유형 
 - 스칼라(scalar) : 하나의 숫자로 이루어진 데이터
 - 벡터(vector) : 여러 개의 숫자로 이루어진 데이터 (data record)
 - 행렬(maxtrix) : 벡터가 여러개 있는 데이터 집합

'''

In [13]:
import numpy as np

In [14]:
# 스칼라
x = 1
x

1

In [16]:
# 벡터
# numpy에서 벡터를 표현할 때 벡터를 열의 개수가 하나인 2차원 배열 객체로 표현하는 것을 권장

x = np.array([[2], [2], [3]])
x


array([[2],
       [2],
       [3]])

In [17]:
# 1차원 배열 객체도 대부분 vector로 인정.
x = np.array([2, 2, 3])
x

array([2, 2, 3])

In [18]:
# 행렬
# 복수의 데이터 집합을 행렬로 표현

# 전치 행렬 : 행렬에서 가장 기본이 되는 연산 (행과 열을 바꾸는 연산)
#          : 전치 연산으로 만들어진 행렬을 원래 행렬에 대한 전치행렬이라고 부릅니다

x = np.array([[2, 2], [3, 3], [4, 4], [5, 5]])
x

array([[2, 2],
       [3, 3],
       [4, 4],
       [5, 5]])

In [19]:
x.T       # T 속성(Attribute)을 이용하여 전치 행렬을 적용 . T가 메소드가 아님에 유의

array([[2, 3, 4, 5],
       [2, 3, 4, 5]])

In [20]:
x = np.array([[2], [2], [3]])
x

array([[2],
       [2],
       [3]])

In [21]:
x.T             # 벡터에 대한 전치 연산 결과는 행이 1개인 행렬이 되고, 이를 행 벡터 (row vector)

array([[2, 2, 3]])

In [22]:
x = np.array([2, 2, 3])
x

array([2, 2, 3])

In [23]:
x.T            # rank가 1인 ndarray는 전치 연산이 정의되지 않는다

array([2, 2, 3])

In [ ]:
'''
# 특수한 벡터와 행렬
# 영벡터 : 모든 원소가 0인 n차원 벡터
  일벡터 : 모든 원소가 1인 n차원 벡터
  
# 정방행렬(square matrix)
 : 행의 개수와 열의 개수가 같은 행렬

# 대각행렬 : 모든 비대각 요소(off-diagonal)가 0인 정방 행렬
          : np.diag

 - 단위행렬 : 대각행렬 중에서 모든 대각요소(주요소)값이 1인 대각행렬 (identity matrix)
           : np.identity, np.eye

# 대칭행렬 : 전치 연산을 통해서 얻은 전치행렬과 원래의 행렬이 같은 경우 (sysmmetric matrix)
          : 정방행렬만이 될 수 있다. 
'''

In [25]:
# 대각행렬
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [26]:
# 단위행렬
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
I = np.identity(3)

In [30]:
np.diag(I)

array([1., 1., 1.])

# 내적

In [ ]:
'''
# 벡터의 내적
# 벡터의 공간에서 정의된 이중 선형(bilinear) 함수의 일종. inner product 또는 dot product라고 부름
# 행렬 곱셉의 결과행렬은 앞 행렬의 행벡터와 뒤 행렬의 열벡터를 내적한 값을 스칼라로 가지는 행렬
'''

In [31]:
# 행렬
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

In [33]:
# 벡터
v = np.array([9, 10])
w = np.array([11, 12])

In [34]:
# 벡터의 내적
v.dot(w)    

219

In [35]:
np.dot(v, w)

219

In [40]:
# 매트릭스 벡터 내적
print(x)
print('--------------')
print(v)

[[1 2]
 [3 4]]
--------------
[ 9 10]


In [41]:
x.dot(v)

array([29, 67])

In [42]:
np.dot(x, v)

array([29, 67])

In [43]:
# 매트릭스 , 매트릭스 내적
x.dot(y)

array([[19, 22],
       [43, 50]])

In [44]:
np.dot(x, y)

array([[19, 22],
       [43, 50]])

# BroadCasting

In [ ]:
'''
# 모양(shape)이 다른 배열들 간의 연산이 어떤 조건을 만족했을 때 가능하도록 배열을 자동적으로 변환하는 것

# ex)
1 2            +  10  10
3 4               10  10

# 브로드캐스팅이 일어날 수 있는 조건
 - 차원 크기가 1, 즉 스칼라면 가능
 - 차원 크기가 1이 아니라면 차원의 짝이 맞는 조건 (축의 길이가 같을 때 등등)
'''

In [45]:
import numpy as np

In [47]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [48]:
b = 10

In [49]:
a + b         # 자동으로 브로드캐스팅이 적용된 상태

array([[11, 12],
       [13, 14]])

In [50]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 2])

In [51]:
a + b              # 브로드캐스팅 적용하려면 한쪽이 스칼라가 기본

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [52]:
x = np.arange(3)
y = 5

In [53]:
x + y

array([5, 6, 7])

In [55]:
x = np.ones((3, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [56]:
y = np.arange(3)
y

array([0, 1, 2])

In [57]:
x + y

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [58]:
x = np.arange(3).reshape(3, 1)
x

array([[0],
       [1],
       [2]])

In [59]:
x + y

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [ ]:
# 3차원 배열

In [61]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[13, 14, 15, 16],
               [17, 18, 19, 20],
               [21, 22, 23, 24]]])
d              

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [63]:
print(len(d)) # 깊이
print(len(d[0])) # 행
print(len(d[0][0])) # 열

2
3
4


In [66]:
# 1로 채운 3차원 배열
d = np.ones((2, 3, 4), dtype='i')       # (깊이, 행, 열)
d

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [65]:
# 다른 배열과 같은 형태의 배열을 만들고 싶을 때 : ones_like
d2 = np.ones_like(d, dtype='f')
d2

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

In [67]:
# 같은 형태 배열 : copy()
copy = np.copy(d); copy

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [68]:
# 대입으로도 가능
copy2 = copy
copy2

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [72]:
# 3차원도 브로드캐스팅 가능
d3 = np.ones((3, 4, 2))
d3

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [73]:
d2 = np.array([[0, 1], [2, 3], [3, 4], [5, 6]])
d2

array([[0, 1],
       [2, 3],
       [3, 4],
       [5, 6]])

In [74]:
d3 + d2

array([[[1., 2.],
        [3., 4.],
        [4., 5.],
        [6., 7.]],

       [[1., 2.],
        [3., 4.],
        [4., 5.],
        [6., 7.]],

       [[1., 2.],
        [3., 4.],
        [4., 5.],
        [6., 7.]]])