In [ ]:
'''
# sort 명령이나 메소드를 사용하여 배열 안의 원소를 크기에 따라 정렬하면 새로운 배열을 만들 수 있다는 아이디어
  2차원 이상인 경우는 행이나 열을 각각 따로 정렬할 수 있음. axis 인수 이용하여 결정
  axis=0 : 열 정렬, axis = 1 : 행 정렬
'''

In [1]:
import numpy as np

In [3]:
a = np.array([[4, 3, 5, 6],
             [1, 12, 11, 9],
              [2, 15, 1, 18]])

a

array([[ 4,  3,  5,  6],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 18]])

In [4]:
np.sort(a)    # default : 행 정렬

array([[ 3,  4,  5,  6],
       [ 1,  9, 11, 12],
       [ 1,  2, 15, 18]])

In [7]:
np.sort(a, axis=0)

array([[ 1,  3,  1,  6],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 18]])

In [9]:
np.sort(a, axis=1)

array([[ 3,  4,  5,  6],
       [ 1,  9, 11, 12],
       [ 1,  2, 15, 18]])

In [12]:
# argsort() : 인덱스 번호가 정렬 되었을 때 어떤 순서로 정렬될 지 그 인덱스 번호만 알려주는 함수
b = np.array([4, 3, 1, 2])
b

array([4, 3, 1, 2])

In [13]:
i = np.argsort(b)
print(i)

[2 3 1 0]


In [14]:
b[i]

array([1, 2, 3, 4])

In [ ]:
'''
# 배열 나누기 (쪼개기) : split()
'''

In [15]:
a = np.array([1, 2, 3])
b = np.array([3, 2, 3])

In [16]:
# 배열 : column_stack()
np.column_stack((a, b))

array([[1, 3],
       [2, 2],
       [3, 3]])

In [17]:
c = np.array([4, 6, 5])

In [18]:
np.column_stack((a, b, c))

array([[1, 3, 4],
       [2, 2, 6],
       [3, 3, 5]])

In [19]:
# 배열 쪼개기
x = np.arange(9); x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
np.split(x, 3)    # 각 값을 3등분해서 새로운 배열로 만들기

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [21]:
y = np.split(x, 3); y

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [22]:
print(y[0])
print(y[1])
print(y[2])

[0 1 2]
[3 4 5]
[6 7 8]


In [24]:
# 요소 나누기
x2 = np.split(x, [3, 4])  # [3, 4] : x 배열의 인덱스 번호를 여러개 선택해서 나눌 수 있음
x2

[array([0, 1, 2]), array([3]), array([4, 5, 6, 7, 8])]

In [25]:
x3 = np.split(x, [2, 5, 7])
x3

[array([0, 1]), array([2, 3, 4]), array([5, 6]), array([7, 8])]

In [26]:
x4 = np.split(x, [2, 4, 10])  # 없는 인덱스 번호로 나누는 것은 pass
x4

[array([0, 1]), array([2, 3]), array([4, 5, 6, 7, 8]), array([], dtype=int32)]

In [27]:
# split = array_split
x5 = np.array_split(x, [2, 4, 10])
x5

[array([0, 1]), array([2, 3]), array([4, 5, 6, 7, 8]), array([], dtype=int32)]

In [28]:
y = np.arange(16).reshape(2, 2, 4); y

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [29]:
# dsplit : 다른 차원을 같은 열 기준으로 같이 나눠서 묶기
y1 = np.dsplit(y, 2); y1

[array([[[ 0,  1],
         [ 4,  5]],
 
        [[ 8,  9],
         [12, 13]]]),
 array([[[ 2,  3],
         [ 6,  7]],
 
        [[10, 11],
         [14, 15]]])]

In [30]:
z = np.arange(16).reshape(4, 4); z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
# hsplit : 차원을 열별로 나누기
z1 = np.hsplit(z, 2); z1

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [32]:
z2 = np.hsplit(z, [2, 5]); z2

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]),
 array([], shape=(4, 0), dtype=int32)]

In [33]:
# 고차원을 열 별로 나누기
h = np.arange(8).reshape(2, 2, 2); h

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [34]:
h1 = np.hsplit(h, 2); h1

[array([[[0, 1]],
 
        [[4, 5]]]),
 array([[[2, 3]],
 
        [[6, 7]]])]

In [36]:
# vsplit : 행으로 나누기
v = np.arange(16).reshape(4, 4); v

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
v1 = np.vsplit(v, 2); v1

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [38]:
v2 = np.vsplit(v, [1, 3]); v2

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [39]:
# 고차원 행으로 나누기
v3 = np.arange(8).reshape(2, 2, 2); v3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [40]:
v4 = np.vsplit(v3, 2); v4

[array([[[0, 1],
         [2, 3]]]),
 array([[[4, 5],
         [6, 7]]])]

In [ ]:
'''
# 요소에 대한 추가 / 삭제
'''

In [41]:
import numpy as np

In [42]:
# 삭제 : np.delete(원데이터, index, axis)
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]); arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
arr1 = np.delete(arr, 1); arr1         # 전체를 한 집합으로 보고 인덱스 1번을 삭제

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [44]:
arr2 = np.delete(arr, 1, 0); arr2

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [45]:
arr3 = np.delete(arr, 2, 1); arr3

array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 10, 12]])

In [ ]:
# 추가 : insert (원데이터, index, 추가할데이터, axis)

In [46]:
a = np.array([[1, 1], [2, 2], [3, 3]]); a

array([[1, 1],
       [2, 2],
       [3, 3]])

In [47]:
a1 = np.insert(a, 1, 100); a1

array([  1, 100,   1,   2,   2,   3,   3])

In [48]:
a2 = np.insert(a, 1, 100, axis=1); a2

array([[  1, 100,   1],
       [  2, 100,   2],
       [  3, 100,   3]])

In [49]:
a3 = np.insert(a, 1, 100, axis=0); a3

array([[  1,   1],
       [100, 100],
       [  2,   2],
       [  3,   3]])

In [51]:
a4 = np.insert(a, 1, [100, 200, 300], axis=1); a4  # 서로 다른 값을 추가하려면 list 로 지정

array([[  1, 100,   1],
       [  2, 200,   2],
       [  3, 300,   3]])

In [ ]:
# 추가 : append

In [52]:
b = np.array([[1, 2, 3], [4, 5, 6]]); b

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
b2 = np.append(b, [7, 8, 9], axis=0); b2

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [54]:
b2 = np.append(b,[[7, 8,9]], axis=0); b2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
'''
# 기타
'''

In [55]:
# resize
x = np.array([[0, 1], [2, 3]]); x

array([[0, 1],
       [2, 3]])

In [56]:
# 2행 3열로 재배치
x1 = np.resize(x, (2, 3)); x1

array([[0, 1, 2],
       [3, 0, 1]])

In [57]:
# 2행 4열로 재배치
x2 = np.resize(x, (2, 4)); x2

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [58]:
# trim_zeros : 0 제거
x = np.array([0, 0, 0, 1, 2, 3, 0, 1, 2, 0, 0]); x

array([0, 0, 0, 1, 2, 3, 0, 1, 2, 0, 0])

In [59]:
x1 = np.trim_zeros(x); x1      # default : 좌우에 연속된 0을 제거

array([1, 2, 3, 0, 1, 2])

In [60]:
x2 = np.trim_zeros(x, 'f')    # f : front   / 'b' : back
x2

array([1, 2, 3, 0, 1, 2, 0, 0])

In [61]:
# unique
x = np.array([1, 1, 2, 1, 2, 2, 3, 3, 3]); x

array([1, 1, 2, 1, 2, 2, 3, 3, 3])

In [62]:
x1 = np.unique(x); x1

array([1, 2, 3])

In [64]:
x = np.array([[1, 1], [2, 3]]); x

array([[1, 1],
       [2, 3]])

In [65]:
x1 = np.unique(x); x1

array([1, 2, 3])

In [66]:
x = np.array([[1, 0, 0], [1, 0, 0], [2, 3, 4]]); x

array([[1, 0, 0],
       [1, 0, 0],
       [2, 3, 4]])

In [67]:
x2 = np.unique(x); x2

array([0, 1, 2, 3, 4])

In [68]:
x3 = np.unique(x, axis=0); x3 

array([[1, 0, 0],
       [2, 3, 4]])

In [ ]:
# 데이터 카운팅 : unique (return_counts)

In [2]:
x4 = np.unique([1, 1, 2, 2, 3, 3]); x4

array([1, 2, 3])

In [3]:
x5 = np.array([1, 1, 2, 2, 2, 3, 3])
x6 = np.unique(x5, return_counts=True); x6

(array([1, 2, 3]), array([2, 3, 2], dtype=int64))

In [4]:
data, count = x6
print(data)
print(count)

[1 2 3]
[2 3 2]


In [5]:
x7 = np.array(['a', 'b', 'b', 'c', 'a', 'd'])
x8 = np.unique(x7, return_counts=True); x8

(array(['a', 'b', 'c', 'd'], dtype='<U1'), array([2, 2, 1, 1], dtype=int64))

In [6]:
data, count = x8
print(data, count)

['a' 'b' 'c' 'd'] [2 2 1 1]


In [ ]:
# bincount
# 주사위 : 나올 수 있는 숫자 1~6
# unique : 주사위를 던졌을 때 나온 숫자만 카운트
# bincount : 나오지 않은 숫자(나올 수 있는 숫자) 는 숫자 카운트를 0으로 한다

In [7]:
cnt = np.bincount([1, 1, 2, 2, 3, 4], minlength=6)
cnt

array([0, 2, 2, 1, 1, 0], dtype=int64)

In [ ]:
# flip : 재정렬 (원본데이터, axis)

In [69]:
x = np.arange(8).reshape((2, 2, 2)); x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [70]:
x1 = np.flip(x, 0); x1      # 차원 기준

array([[[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

In [71]:
x2 = np.flip(x, 1); x2     # 행 기준

array([[[2, 3],
        [0, 1]],

       [[6, 7],
        [4, 5]]])

In [72]:
x3 = np.flip(x, 2); x3      # 열 기준

array([[[1, 0],
        [3, 2]],

       [[5, 4],
        [7, 6]]])

In [ ]:
# fliplr

In [73]:
x = np.diag([1, 2, 3]); x

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [74]:
x1 = np.fliplr(x); x1

array([[0, 0, 1],
       [0, 2, 0],
       [3, 0, 0]])

In [75]:
# cf) diag - 
d = np.arange(9).reshape((3, 3)); d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [76]:
np.diag(d)      # default : (0, 0)

array([0, 4, 8])

In [77]:
np.diag(d, k=1)    # k : 대각선 시작점

array([1, 5])

In [78]:
np.diag(d, k=-1)

array([3, 7])

In [ ]:
# flipud 

In [79]:
x = np.diag([1, 2, 3]); x

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [80]:
x1 = np.flipud(x); x1

array([[0, 0, 3],
       [0, 2, 0],
       [1, 0, 0]])

In [ ]:
# rot90 : 90도만큼 배열 요소 회전 (k : 90도를 몇번 회전, axes : (가로,세로))

In [81]:
r = np.array([[1, 2], [3, 4]]); r

array([[1, 2],
       [3, 4]])

In [82]:
r1 = np.rot90(r, 1); r1  # 회전방향 : 반시계 방향

array([[2, 4],
       [1, 3]])

In [83]:
r2 = np.rot90(r); r2

array([[2, 4],
       [1, 3]])

In [84]:
r3 = np.rot90(r, 1, (1, 0)); r3        # 시계방향

array([[3, 1],
       [4, 2]])

In [85]:
r4 = np.rot90(r, 2, (1, 0)); r4       # 시계방향, 180도 회전

array([[4, 3],
       [2, 1]])

In [86]:
r5 = np.rot90(r, -1, (0, 1)); r5

array([[3, 1],
       [4, 2]])